In [80]:
import numpy as np
from itertools import permutations, combinations, product
from functools import reduce
from math import factorial
from sympy.solvers import solve
from sympy import Symbol

In [2]:
D = 3
bases = np.eye(D)
permutation_bases = list(permutations(bases,D))

In [3]:
#Get all permutation matrices
perm_matrices = []
for perm in permutation_bases:
    perm_matrices.append(np.array([elem.tolist() for elem in perm]))

In [86]:
#Assign probabilities to each matrix
probs = np.random.rand(len(perm_matrices))
probs = probs/np.sum(probs)
probs = np.array([0.2,0.1,0.4,0,0.2,0.1])
probs = np.array([0.2571428571428572, 0.042857142857142864, 0.34285714285714286, 0.057142857142857134, 0.2571428571428572, 0.042857142857142864])
# probs = np.array([0.25,0.05,0.35,0.05,0.25,0.05])
# probs = np.array([0,0.1,0.15,0.2,0.25,0.3])
# probs = np.array([0.054, 0.014, 0.811, 0.054, 0.054, 0.014])
# probs = np.array([0.9,0,0,0.1,0,0])

In [87]:
#Compute probabilities of each term in a permutation matrix being one
probs_elements = np.sum([p*matrix for p, matrix in zip(probs, perm_matrices)],0)

In [88]:
#Compute unnormalized probabilities of each matrix
# unnorm_probs = np.array([np.sum(probs_elements*matrix) for matrix in perm_matrices]) #With sum of elements
unnorm_probs = np.array([np.prod(np.sum(probs_elements*matrix,0)) for matrix in perm_matrices]) #With prod of elements

In [89]:
unnorm_probs

array([0.054, 0.009, 0.144, 0.004, 0.054, 0.009])

In [90]:
print(probs)
print(unnorm_probs)
print(unnorm_probs/np.sum(unnorm_probs))

[0.25714286 0.04285714 0.34285714 0.05714286 0.25714286 0.04285714]
[0.054 0.009 0.144 0.004 0.054 0.009]
[0.19708029 0.03284672 0.52554745 0.01459854 0.19708029 0.03284672]


In [91]:
a = np.zeros(factorial(D))
for nn, (x,y) in enumerate(zip(probs,unnorm_probs)):
    if y == 0:
        a[nn] = 0
    else:
        a[nn] = x/y

In [92]:
0.1**3

0.0010000000000000002

In [93]:
probs

array([0.25714286, 0.04285714, 0.34285714, 0.05714286, 0.25714286,
       0.04285714])

In [94]:
probs_elements

array([[0.3, 0.4, 0.3],
       [0.6, 0.3, 0.1],
       [0.1, 0.3, 0.6]])

In [70]:
perm_matrices

[array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1., 0., 0.],
        [0., 0., 1.],
        [0., 1., 0.]]),
 array([[0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.]]),
 array([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]]),
 array([[0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.]]),
 array([[0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.]])]

In [85]:
b1 = probs_elements[2,2]/(probs_elements[1,2]+probs_elements[2,2])
b2 = probs_elements[1,2]/(probs_elements[1,2]+probs_elements[2,2])
c3 = probs_elements[0,2]
c1 = (probs_elements[1,1]-probs_elements[0,2]*(1-probs_elements[1,0]))/probs_elements[2,2]
c2 = ((probs_elements[0,1]-probs_elements[2,0])*(1-probs_elements[0,2]) + probs_elements[0,2]*probs_elements[1,2])/probs_elements[2,2]
print([b1, b2])
print([c1, c2, c3])
print(list(map(np.prod,product([c1,c2,c3],[b1,b2]))))

[0.8571428571428572, 0.14285714285714285]
[0.30000000000000004, 0.39999999999999997, 0.30000000000000004]
[0.2571428571428572, 0.042857142857142864, 0.34285714285714286, 0.057142857142857134, 0.2571428571428572, 0.042857142857142864]


In [46]:
a_2 = probs[1]+probs[2]+probs[5]
a_1 = probs[1]*probs[2] + probs[1]*probs[5] + probs[5]*probs[2]
a_0 = probs[1]*probs[2]*probs[5] - unnorm_probs[3]

In [47]:
x = Symbol('x')
solve(x**3 +x**2*a_2 + x*a_1 + a_0, x)

[-0.300000000000000, 0.0]

In [48]:
unnorm_probs

array([0.054, 0.009, 0.144, 0.004, 0.054, 0.009])

In [49]:
probs

array([0.2, 0.1, 0.4, 0. , 0.2, 0.1])